### ISSUE TITLE
KeyError: 'fpbpn’ when training with PointNet as the image feature extractor

### ISSUE THREAD

**Issue by CircleAAA** [MIT-SPARK/MiDiffusion#3]
I switched from ResNet18 to PointNet, as said in your paper that PointNet better captures floor boundary. Besides, as presented in the paper, DDPM+PointNet has lower KL-divergence than DDPM+ResNet, which indicates that PointNet might help in fitting the underlying probability distribution. I was curious how mush PointNet helps in MiDiffusion, so I simply switched to PointNet. Unfortunately, KeyError: 'fpbpn' occured at the line 47 of networks\diffusion_scene_layout_mixed.py
`room_feature = sample_params["fpbpn"]`

May I ask if I missed any procedure to preprocess the data so as to train with PointNet as the image feature extractor?

**Comment by CircleAAA** [comment]
And I saw the room mask is mapped into a 64 dimensional vector embedding. To me, saving the room boundary polygon coordinates into a \R^{64} vector is much more simple and straight.

**Comment by Xmy1120** [comment]
> And I saw the room mask is mapped into a 64 dimensional vector embedding. To me, saving the room boundary polygon coordinates into a \R^{64} vector is much more simple and straight.

Have you solved this problem? I have the same problem

**Comment by CircleAAA** [comment]
> > And I saw the room mask is mapped into a 64 dimensional vector embedding. To me, saving the room boundary polygon coordinates into a \R^{64} vector is much more simple and straight.
> 
> Have you solved this problem? I have the same problem

well，I suggest you just use resnet18

**Comment by SiyiHu** [comment]
Most likely you are missing the step to convert the room mask image to `fpbpn` (denoted as `floor_plan_boundary_points_normals` in [ThreedFront](https://github.com/MIT-SPARK/ThreedFront) repo). Please refer to [this step](https://github.com/MIT-SPARK/ThreedFront?tab=readme-ov-file#optional-sample-floor-plan-boundary). 

This script first computes `floor_plan_ordered_corners`, which are ordered corner coordinates of each floor plan, and then samples a fixed number (default:256) of boundary points to ensure the floor plan features are of the same size. The number of corners can have a pretty big range due to curvy floor boundaries.
