### ISSUE TITLE
did the network really learn distribution of unordered set ?

### ISSUE THREAD

**Issue by Starry-lei** [MIT-SPARK/MiDiffusion#5]
Hi there,

Thank you for the open-sourcing code. I have a related question I'd like to discuss: given that the categorical dataset is unordered (implying N! kinds of order), this results in a very sparse data distribution. Can the model really learn from such a sparse data distribution?

Looking forward to your insights.

**Comment by SiyiHu** [comment]
I am not sure if I fully understand the question. 
Our default implementation trains the model with permutation augmentation and then trained model predicts a list of objects rather than an unordered set. This is due to empirical results. Conceptually, it is more straight-forward to learn to predict a  set. If you are interested, you can set "position_condition" in the config files to false such that the denoising network is invariant to object ordering. You can also add "_no_prm" to the end of "encoding_type" to turn off permutation augmentation. This should not make any difference if "position_condition" is set to false but might save some training time.

**Comment by SiyiHu** [comment]
We decided to change "position_condition" to "false" in the default config. This does affect the floor conditioned scene synthesis results. The main difference is that it removes the second normalization layer and the second MH attention unit (which takes in the condition features) in each transformer block in the unconditioned case. We found this change yields better unconditioned scene synthesis results.
